rppg_toolbox_node:
  ros__parameters:
    frame_rate: 30
    algo: 'pos'
    estimate: 'fft'
    window_secs: 3
    overlap_secs: 2
    camera_topic: '/camera'
    topic: '/heart_rate_bpm'
    rppgtb_path: '/home/mscrobotics2425laptop11/Dissertation/rppgtb/rPPG-Toolbox'
    video_path: '/home/mscrobotics2425laptop11/Dissertation/UBFC/RawData/subject1/vid.avi'
    img_height: 96
    img_width: 128
    roi_area: 'forehead'